/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#f0eee6",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary-fixed": "#001a42",
        "tertiary-fixed": "#ffddb8",
        "on-error": "#ffffff",
        "on-background": "#1b1c17",
        "surface-container-low": "#f5f4ec",
        "on-primary": "#ffffff",
        secondary: "#006c49",
        "inverse-primary": "#adc6ff",
        surface: "#fbf9f1",
        "primary-fixed-dim": "#adc6ff",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-variant": "#004395",
        "inverse-surface": "#30312c",
        "outline-variant": "#c2c6d6",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00714d",
        "error-container": "#ffdad6",
        "primary-container": "#2170e4",
        "tertiary-fixed-dim": "#ffb95f",
        primary: "#0058be",
        "secondary-container": "#6cf8bb",
        "on-secondary": "#ffffff",
        "surface-bright": "#fbf9f1",
        "on-surface-variant": "#424754",
        "surface-variant": "#e4e3db",
        background: "#fbf9f1",
        "on-tertiary-container": "#fffbff",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#825100",
        "on-primary-container": "#fefcff",
        "on-primary-fixed-variant": "#004395",
        "surface-dim": "#dcdad2",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#eae8e0",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "surface-tint": "#005ac2",
        "on-surface": "#1b1c17",
        "on-secondary-fixed": "#002113",
        "secondary-fixed": "#6ffbbe",
        outline: "#727785",
        "surface-container-highest": "#e4e3db",
        "on-error-container": "#93000a",
        "tertiary-container": "#a36700",
        "inverse-on-surface": "#f3f1e9",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "container-max": "1200px",
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg-mobile": ["Lexend", "sans-serif"],
        "label-sm": ["Lexend", "sans-serif"],
        "display-lg": ["Lexend", "sans-serif"],
        "headline-md": ["Lexend", "sans-serif"],
        "body-md": ["Quicksand", "sans-serif"],
        "body-lg": ["Quicksand", "sans-serif"],
      },
      fontSize: {
        "display-lg-mobile": [
          "32px",
          {
            lineHeight: "1.2",
            fontWeight: "700",
          },
        ],
        "label-sm": [
          "14px",
          {
            lineHeight: "1.2",
            fontWeight: "600",
          },
        ],
        "display-lg": [
          "48px",
          {
            lineHeight: "1.2",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "24px",
          {
            lineHeight: "1.4",
            fontWeight: "600",
          },
        ],
        "body-md": [
          "16px",
          {
            lineHeight: "1.6",
            fontWeight: "500",
          },
        ],
        "body-lg": [
          "18px",
          {
            lineHeight: "1.6",
            fontWeight: "500",
          },
        ],
      },
    },
  },
  plugins: [],
};
