// <auto-generated />
using System;
using ChemistryV1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChemistryV1.Migrations
{
    [DbContext(typeof(ElearningDbContext))]
    partial class ElearningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChemistryV1.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Categories__3213E83F6C7A1D42");

                    b.HasIndex(new[] { "Slug" }, "UQ__Categories__32DD1E4C8A4C9D5D")
                        .IsUnique()
                        .HasFilter("[slug] IS NOT NULL");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ChemistryV1.Models.Chapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Chapters__3213E83F70D5FB42");

                    b.HasIndex("CourseId");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("ChemistryV1.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicYear")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("academic_year");

                    b.Property<string>("ClassName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("class_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("school_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id")
                        .HasName("PK__Classes__3213E83F9453FEDF");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("ChemistryV1.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Comments__3213E83F953618EC");

                    b.HasIndex("LessonId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ChemistryV1.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Courses__3213E83F9B7447CC");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "Slug" }, "UQ__Courses__32DD1E4C7A390565")
                        .IsUnique()
                        .HasFilter("[slug] IS NOT NULL");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ChemistryV1.Models.CourseCategory", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.HasKey("CourseId", "CategoryId")
                        .HasName("PK__CourseCa__4D2C2B7B4E6B5F6A");

                    b.HasIndex("CategoryId");

                    b.ToTable("CourseCategories", (string)null);
                });

            modelBuilder.Entity("ChemistryV1.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("EnrolledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("enrolled_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("CourseId", "StudentId")
                        .HasName("PK__CourseEn__3DBDC7C75CEDBEA2");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseEnrollments");
                });

            modelBuilder.Entity("ChemistryV1.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("attachment_path");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int")
                        .HasColumnName("chapter_id");

                    b.Property<bool?>("CommentsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("comments_enabled");

                    b.Property<string>("ContentType")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("document_content");

                    b.Property<bool?>("IsPreview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_preview");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("pdf_path");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("video_url");

                    b.Property<int?>("VirtualLabId")
                        .HasColumnType("int")
                        .HasColumnName("virtual_lab_id");

                    b.HasKey("Id")
                        .HasName("PK__Lessons__3213E83FF831917F");

                    b.HasIndex("ChapterId");

                    b.HasIndex("VirtualLabId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ChemistryV1.Models.LessonSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("file_url");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("SubmissionContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("submission_content");

                    b.Property<string>("TeacherComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("teacher_comment");

                    b.HasKey("Id")
                        .HasName("PK__LessonSu__3213E83F97CEA58B");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonSubmissions");
                });

            modelBuilder.Entity("ChemistryV1.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("published")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__News__3213E83F22E97CF4");

                    b.HasIndex("AuthorId");

                    b.ToTable("News");
                });

            modelBuilder.Entity("ChemistryV1.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("Options")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("options");

                    b.HasKey("Id")
                        .HasName("PK__Question__3213E83F8E9E37ED");

                    b.HasIndex("CourseId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("ChemistryV1.Models.QuizDetailedAnswer", b =>
                {
                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit")
                        .HasColumnName("is_correct");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<int?>("QuizResultId")
                        .HasColumnType("int")
                        .HasColumnName("quiz_result_id");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selected_answer");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizResultId");

                    b.ToTable("QuizDetailedAnswers");
                });

            modelBuilder.Entity("ChemistryV1.Models.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("RevisionId")
                        .HasColumnType("int")
                        .HasColumnName("revision_id");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("TotalCorrect")
                        .HasColumnType("int")
                        .HasColumnName("total_correct");

                    b.HasKey("Id")
                        .HasName("PK__QuizResu__3213E83F14D601C3");

                    b.HasIndex("RevisionId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("ChemistryV1.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("token");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__RefreshT__3213E83FC0ACB173");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ChemistryV1.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK__Reviews__3213E83F5D5CE2D7");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ChemistryV1.Models.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("TimeLimit")
                        .HasColumnType("int")
                        .HasColumnName("time_limit");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK__Revision__3213E83F21E19BFF");

                    b.HasIndex("CourseId");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("ChemistryV1.Models.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__Schools__3213E83F5E9E8405");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("ChemistryV1.Models.SystemMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("color_class");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("MetricKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("metric_key");

                    b.Property<string>("RewardText")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reward_text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<int>("TargetValue")
                        .HasColumnType("int")
                        .HasColumnName("target_value");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_SystemMissions");

                    b.ToTable("SystemMissions", (string)null);
                });

            modelBuilder.Entity("ChemistryV1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<bool?>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<string>("EmailVerificationCodeHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email_verification_code_hash");

                    b.Property<DateTime?>("EmailVerificationExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("email_verification_expires_at");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<int?>("SchoolId")
                        .HasColumnType("int")
                        .HasColumnName("school_id");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83F2D6B6E9F");

                    b.HasIndex("SchoolId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__F3DBC572952E5D47")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChemistryV1.Models.UserLessonProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("LessonId")
                        .HasColumnType("int")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.HasKey("UserId", "LessonId")
                        .HasName("PK__UserLess__4FFC2874919332CA");

                    b.HasIndex("LessonId");

                    b.ToTable("UserLessonProgress", (string)null);
                });

            modelBuilder.Entity("ChemistryV1.Models.VirtualLab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("VirtualLabs", (string)null);
                });

            modelBuilder.Entity("ClassMember", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ClassId", "StudentId")
                        .HasName("PK__ClassMem__4F5749EF5D1F6D2E");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassMembers", (string)null);
                });

            modelBuilder.Entity("RevisionQuestion", b =>
                {
                    b.Property<int>("RevisionId")
                        .HasColumnType("int")
                        .HasColumnName("revision_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.HasKey("RevisionId", "QuestionId")
                        .HasName("PK__Revision__8156D1518CAD8F80");

                    b.HasIndex("QuestionId");

                    b.ToTable("RevisionQuestions", (string)null);
                });

            modelBuilder.Entity("ChemistryV1.Models.Chapter", b =>
                {
                    b.HasOne("ChemistryV1.Models.Course", "Course")
                        .WithMany("Chapters")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Chapters_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ChemistryV1.Models.Class", b =>
                {
                    b.HasOne("ChemistryV1.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("SchoolId")
                        .HasConstraintName("FK_Classes_Schools");

                    b.HasOne("ChemistryV1.Models.User", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_Classes_Users");

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ChemistryV1.Models.Comment", b =>
                {
                    b.HasOne("ChemistryV1.Models.Lesson", "Lesson")
                        .WithMany("Comments")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK_Comments_Lessons");

                    b.HasOne("ChemistryV1.Models.Comment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Comments_Parent");

                    b.HasOne("ChemistryV1.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Comments_Users");

                    b.Navigation("Lesson");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChemistryV1.Models.Course", b =>
                {
                    b.HasOne("ChemistryV1.Models.User", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK_Courses_Users");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ChemistryV1.Models.CourseCategory", b =>
                {
                    b.HasOne("ChemistryV1.Models.Category", "Category")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseCategories_Categories");

                    b.HasOne("ChemistryV1.Models.Course", "Course")
                        .WithMany("CourseCategories")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseCategories_Courses");

                    b.Navigation("Category");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ChemistryV1.Models.CourseEnrollment", b =>
                {
                    b.HasOne("ChemistryV1.Models.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseEnrollments_Courses");

                    b.HasOne("ChemistryV1.Models.User", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseEnrollments_Users");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ChemistryV1.Models.Lesson", b =>
                {
                    b.HasOne("ChemistryV1.Models.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .HasConstraintName("FK_Lessons_Chapters");

                    b.HasOne("ChemistryV1.Models.VirtualLab", "VirtualLab")
                        .WithMany("Lessons")
                        .HasForeignKey("VirtualLabId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Lessons_VirtualLabs");

                    b.Navigation("Chapter");

                    b.Navigation("VirtualLab");
                });

            modelBuilder.Entity("ChemistryV1.Models.LessonSubmission", b =>
                {
                    b.HasOne("ChemistryV1.Models.Lesson", "Lesson")
                        .WithMany("LessonSubmissions")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("FK_LessonSubmissions_Lessons");

                    b.HasOne("ChemistryV1.Models.User", "Student")
                        .WithMany("LessonSubmissions")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_LessonSubmissions_Users");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ChemistryV1.Models.News", b =>
                {
                    b.HasOne("ChemistryV1.Models.User", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK_News_Users");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ChemistryV1.Models.Question", b =>
                {
                    b.HasOne("ChemistryV1.Models.Course", "Course")
                        .WithMany("Questions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Questions_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ChemistryV1.Models.QuizDetailedAnswer", b =>
                {
                    b.HasOne("ChemistryV1.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK_QuizDetailedAnswers_Questions");

                    b.HasOne("ChemistryV1.Models.QuizResult", "QuizResult")
                        .WithMany()
                        .HasForeignKey("QuizResultId")
                        .HasConstraintName("FK_QuizDetailedAnswers_QuizResults");

                    b.Navigation("Question");

                    b.Navigation("QuizResult");
                });

            modelBuilder.Entity("ChemistryV1.Models.QuizResult", b =>
                {
                    b.HasOne("ChemistryV1.Models.Revision", "Revision")
                        .WithMany("QuizResults")
                        .HasForeignKey("RevisionId")
                        .HasConstraintName("FK_QuizResults_Revisions");

                    b.HasOne("ChemistryV1.Models.User", "Student")
                        .WithMany("QuizResults")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_QuizResults_Users");

                    b.Navigation("Revision");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ChemistryV1.Models.RefreshToken", b =>
                {
                    b.HasOne("ChemistryV1.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChemistryV1.Models.Review", b =>
                {
                    b.HasOne("ChemistryV1.Models.Course", "Course")
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Reviews_Courses");

                    b.HasOne("ChemistryV1.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Reviews_Users");

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChemistryV1.Models.Revision", b =>
                {
                    b.HasOne("ChemistryV1.Models.Course", "Course")
                        .WithMany("Revisions")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK_Revisions_Courses");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ChemistryV1.Models.User", b =>
                {
                    b.HasOne("ChemistryV1.Models.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .HasConstraintName("FK_Users_Schools");

                    b.Navigation("School");
                });

            modelBuilder.Entity("ChemistryV1.Models.UserLessonProgress", b =>
                {
                    b.HasOne("ChemistryV1.Models.Lesson", "Lesson")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("LessonId")
                        .IsRequired()
                        .HasConstraintName("FK_UserLessonProgress_Lessons");

                    b.HasOne("ChemistryV1.Models.User", "User")
                        .WithMany("UserLessonProgresses")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserLessonProgress_Users");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClassMember", b =>
                {
                    b.HasOne("ChemistryV1.Models.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassMembers_Classes");

                    b.HasOne("ChemistryV1.Models.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_ClassMembers_Users");
                });

            modelBuilder.Entity("RevisionQuestion", b =>
                {
                    b.HasOne("ChemistryV1.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_RevisionQuestions_Questions");

                    b.HasOne("ChemistryV1.Models.Revision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .IsRequired()
                        .HasConstraintName("FK_RevisionQuestions_Revisions");
                });

            modelBuilder.Entity("ChemistryV1.Models.Category", b =>
                {
                    b.Navigation("CourseCategories");
                });

            modelBuilder.Entity("ChemistryV1.Models.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ChemistryV1.Models.Comment", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("ChemistryV1.Models.Course", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("CourseCategories");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("Questions");

                    b.Navigation("Reviews");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ChemistryV1.Models.Lesson", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LessonSubmissions");

                    b.Navigation("UserLessonProgresses");
                });

            modelBuilder.Entity("ChemistryV1.Models.Revision", b =>
                {
                    b.Navigation("QuizResults");
                });

            modelBuilder.Entity("ChemistryV1.Models.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ChemistryV1.Models.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Comments");

                    b.Navigation("CourseEnrollments");

                    b.Navigation("Courses");

                    b.Navigation("LessonSubmissions");

                    b.Navigation("News");

                    b.Navigation("QuizResults");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("UserLessonProgresses");
                });

            modelBuilder.Entity("ChemistryV1.Models.VirtualLab", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
